name: Deploy To EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  Deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

        # Node 설치 (static 라이브러리 npm install용)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Spring Boot JAR
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push app image
        run: |
            docker build --platform linux/amd64 -t lhr5767/studyolle:latest .
            docker push lhr5767/studyolle:latest

      - name: Build & push nginx image
        run: |
          docker build --platform linux/amd64 -t lhr5767/studyolle-nginx:latest ./nginx
          docker push lhr5767/studyolle-nginx:latest

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              cd /home/ubuntu/
              export MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
              export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
              docker compose --profile dev pull
              docker compose --profile dev up -d
